spring.application.name=posto
spring.datasource.url=jdbc:mysql://localhost:3306/post
spring.datasource.username=root
spring.datasource.password=Elevir321

jwt.private=classpath:private.key
jwt.public=classpath:public.key

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true